COMMON_CONST = Import("common/const.lua")
JSON4LUA = Import("common/json.lua")
GAME_MAIN = Import("game_main.lua")
CB_MGR = Import("module/base/cb_mgr.lua")
HTTP = Import("module/base/http.lua")
HTTP_SRV = Import("module/base/http_srv.lua")
